sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - develop # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
after_script:
  - cd ./public
  - git init
  - git config user.name "pysnow530"
  - git config user.email "pysnow530@163.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master # GH_TOKEN是在Travis中配置token的名称
env:
  global:
    - GH_REF: github.com/pysnow530/pysnow530.github.io.git